### PR TITLE
FIX whole page reload when press enter

### PR DESCRIPTION
**Pull request by kmkhant**
fix [#1024](https://github.com/AmruthPillai/Reactive-Resume/issues/1024#issue-1400709220)

This is my first contribution to an open source project. Please guide me if I were wrong.

### CODE REVIEW

**Comment by AmruthPillai** [comment]
That's a good fix, does this occur only in the InterestModal, or is this something we might need in other modals/forms as well?

**Comment by kmkhant** [comment]
As far as I tested, I found page reloading issue when pressed enter only in Interest Modal. But it would be a great user experience if the user can just press enter after filling all the required forms instead of clicking the button.

**Comment by AmruthPillai** [comment]
Let's do it for all the modals, it would be a great help :) Thank you!

**Comment by kmkhant** [comment]
OK, I will update my pr soon thanks for the suggestion <3

**Comment by AmruthPillai** [comment]
Thank you so much for the contribution, will make sure it goes out on the next update! 🔥

**Comment by kmkhant** [comment]
Thank you so much too for creating this great app. I've learned a lot by reading the source code. I'll try to make more contributions in the future.

**Pull request merged**
