### PR TITLE
Adding Contributors Wall to README

### PR DESCRIPTION
**Pull request by GovindKrishnan**
Using an open-source web tool called [contrib.rocks](https://contrib.rocks/preview?repo=AmruthPillai%2FReactive-Resume) that sync daily with [Contributors Club](https://github.com/AmruthPillai/Reactive-Resume/graphs/contributors).

Sort of experimental as I came across this today. But yea, it does no harm to production to say the least. 😅

### CODE REVIEW

**Comment by AmruthPillai** [comment]
@GovindKrishnan I love this change, most welcome :) Just one quick addition: could you add the same on the docs as well, found in `docs/docs/index.mdx`?

**Comment by GovindKrishnan** [comment]
@AmruthPillai Glad you liked it! Have added it to `index.mdx` as well. 😄 👍

**Comment by AmruthPillai** [comment]
LGTM 🚀

**Comment by GovindKrishnan** [comment]
@AmruthPillai However, the reason I said this is **experimental** is that it has a limit of 100 contributors. The tool's website does mention specifying `max=numbers` as URL parameter but when I tried numbers >100 on large repos, profile pictures duplicated. So remember to check its behaviour once we welcome the 101st contributor. If it randomizes the profile pictures during daily refreshes, all good. Else, it might become static. We'll see anyway. We're 60 already! 😄

**Pull request merged**
