### PR TITLE
feat: separate links option to reduce section item height

### PR DESCRIPTION
**Pull request by jzaehrin**
I just discovered this amazing project and I would like to help. I am rusty from the little experience I've had with React. I welcome any advice and opinions. 

This is a Draft of an option to regroup links of section's items:

screenshot-2024-03-21_17-19-09
screenshot-2024-03-21_17-20-39
screenshot-2024-03-21_17-21-12
screenshot-2024-03-21_17-21-26

This is a first idea, but it would also be possible to have the option at the section level. I suppose it would be a good idea to wrap this ternary condition to avoid reading heaviness.

I'm waiting for opinions/suggestions/approvals to complete this work.

To do:
- [x] Adapt all templates with the features

### CODE REVIEW

**Comment by jzaehrin** [comment]
Rework: Better code visibility

**Comment by jzaehrin** [comment]
I moved the option at the section level, the toggle is now present in the dropdown menu per section to have granular options

screenshot-2024-03-25_17-26-54
screenshot-2024-03-25_17-27-05

I finished the full implementation

**Comment by AmruthPillai** [comment]
My apologies, I wanted to merge this too, but there was a conflict. I ran the wrong command which closed the PR. Will update it to the latest branch and get this merged ASAP. Thank you so much for your efforts and the feature, it really is a very useful option! <3

**Comment by jzaehrin** [comment]
> Owner

Sure with pleasure! Have you any suggestions to improve it? I will do the rebase as soon as possible 😃

**Comment by AmruthPillai** [comment]
No, looks really good. I just tried it out locally and works perfectly.

**Pull request merged**
