### PR TITLE
Quick dockerfile implementation

### PR DESCRIPTION
**Pull request by benjaminchodroff**
Awesome project. Saw the request for docker on reddit and thought this may help others. I see I am now 2 hours late... but perhaps my pull request will help you? 

You can install docker, and test by running these commands:
docker build -t reactive-resume .
docker run -p 5000:5000 reactive-resume:latest

### CODE REVIEW

**Comment by AmruthPillai** [comment]
Oh, I am so sorry. I started working on it as soon as I created an issue on GitHub, the only thing slowing me down was my internet connection, but I have managed to successfully push a docker image and the changes required for the same.

You can read more about it in the documentation:
https://docs.rxresu.me/deployment/#docker

I'm really sorry that you had to go through all that trouble. I'll get better with making clear updates on what I'm working on further so that there won't be any clashes, but I do appreciate your efforts a lot and I do hope you keep contributing to the project :) Thank you so so much!

**Comment by benjaminchodroff** [comment]
No problem at all! I'm glad you are pushing forward with this! It's awesome :)
Just some suggestions though - avoid multiple FROM (https://stackoverflow.com/questions/33322103/multiple-froms-what-it-means), declare a USER (don't run as root), and it would be best to leave nginx out of your dockerfile and instead create a docker-compose which uses two separate containers (it seems weird compared to how we used to think about virtual machines, but many want as little as possible in each container). But honestly - great work! Thank you!!!

**Comment by AmruthPillai** [comment]
Yes, I just saw your comment on Reddit. I'm not quite sure on how to do this, as I'm still learning all about Docker. Could you reopen a PR and work around with the files I've made to make them better according to your experience? I would want to strive for maximum efficiency too, and dangling containers are a pain.

Thank you so much :) Please keep supporting, and I'll keep doing whatever I can to make the app more and more useful.

**Comment by AmruthPillai** [comment]
Hey @benjaminchodroff, would you be making that extra fix or should we let this be? :)

**Comment by benjaminchodroff** [comment]
Looks great to me. The nginx+node appears to work well - and is running as nginx. Let's go with what you got!

**Comment by 82jax** [comment]
Is the docker/portainer deployment code avail for this then as it's not obvious from an initial look?  Maybe I'm just missing something.

**Pull request closed without merging**
