### PR TITLE
Add File based Storage toggle for Photos

### PR DESCRIPTION
**Pull request by dvd741-a**
Add toggle env option to toggle between file based or S3 Bucket storage.

### CODE REVIEW

**Comment by dvd741-a** [comment]
@AmruthPillai - Can you have a look at this merge request ... ?

**Comment by AmruthPillai** [comment]
Quite an interesting solution, thank you for your contribution! :)

**Review by AmruthPillai — APPROVED** [review]

**Comment by AmruthPillai** [comment]
@dvd741-a Would you also be able to add the local file storage path to docker volumes, so that on every docker restart/reload, the uploaded images are not erased?

**Comment by dvd741-a** [comment]
> @dvd741-a Would you also be able to add the local file storage path to docker volumes, so that on every docker restart/reload, the uploaded images are not erased?

I would be able to as soon as I can test it :-)
Wasn't able to build the docker image myself using the dockerfile in the repository. If a version gets bumped/built and put on dockerhub, I can try the correct path for the mount

**Comment by michael-robbins** [comment]
I believe inside the container `/app/server/dist/assets/uploads` is the path being referred to in this PR.

So adding something like: `VOLUME /app/server/dist/assets/uploads` inside `server/Dockerfile` should do the trick here!

**Comment by dvd741-a** [comment]
@michael-robbins Can you have a look if this seems correct to you? / Not sure who can approve. - I've already mapped the path to a folder in my instance, as soon as a new version is built & gets put on dockerhub - It should start working.

**Comment by michael-robbins** [comment]
It looks fine to me! I've already updated my setup to use the new env vars as well as the volume!

**Pull request merged**
